/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.laboratorio.java_139_enterprise_javabean_uniendo_componentes_jse_jee_2;

import jakarta.jms.Message;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import tools.jackson.databind.ObjectMapper;

/**
 *
 * @author canzervero
 */
public class PersonasForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonasForm.class.getName());

    /**
     * Creates new form PersonasFrom
     */
    public PersonasForm() {
        initComponents();
        try{
            conectarServidor();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Imposible conectar al servidor",
               "Error",JOptionPane.INFORMATION_MESSAGE);
            System.exit(-1);
        }
    }
    private void conectarServidor() throws Exception {
         

            String usuario = "canzervero";
            String clave = "cuervo";

//        Propiedades para crear el contexto
            Properties entorno = new Properties();
            entorno.put(Context.INITIAL_CONTEXT_FACTORY, "org.wildfly.naming.client.WildFlyInitialContextFactory");
            entorno.put(Context.PROVIDER_URL, "http-remoting://localhost:8080");
            entorno.put(Context.SECURITY_PRINCIPAL, usuario);
            entorno.put(Context.SECURITY_CREDENTIALS, clave);
            
//        Crear el contexto
            
            InitialContext ic = new InitialContext(entorno);

            System.out.println("El contexto inicial ha sido creado");

            String uri = "ejb:/video_132_Enterprise_JavaBean_Introduccion-1.0-SNAPSHOT/BeanForTest!com.laboratorio.video_132_enterprise_javabean_introduccion.ejb.BeanForTestRemote";
//            String uri_134="ejb:/video_134_Enterprise_Bean_Stateles_SessionBean-1.0-SNAPSHOT/BeanConEstado!com.laboratorio.video_134_enterprise_bean_stateles_sessionbean.ejb.stateful.BeanConEstadoRemote?stateful";

            BeanForTestRemote beanRemote = (BeanForTestRemote) ic.lookup(uri);
            System.out.println("Llamada remota: " + beanRemoto.remoteFunction());           
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tFechaNac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tExperiencia = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos de la Persona");

        jLabel1.setText("Nombres:");

        tNombres.setName(""); // NOI18N

        jLabel2.setText("Apellidos: ");

        tApellidos.addActionListener(this::tApellidosActionPerformed);

        jLabel3.setText("Fecha Nacimiento: ");

        jLabel4.setText("Experiencia: ");

        bEnviar.setText("Enviar datos");
        bEnviar.addActionListener(this::bEnviarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tNombres)
                                    .addComponent(tApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bEnviar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(bEnviar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tApellidosActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        String nombres = tNombres.getText();
        String apellidos = tApellidos.getText();
        String fechaNac = tFechaNac.getText();
        String experiencia = tExperiencia.getText();
        
        enviarDatosPersona(nombres, apellidos, fechaNac, experiencia);
        tNombres.setText("");
        tApellidos.setText("");
        tFechaNac.setText("");
        tExperiencia.setText("");
    }//GEN-LAST:event_bEnviarActionPerformed

   private void enviarDatosPersona(String nombres,String apellidos,
                                    String fechaNac, String experiencia){
              
       Date fecha;
       SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
       try{
           fecha = formato.parse(fechaNac);
       }catch(ParseException e){
           fecha = new Date();
       }
       
       int annos;
       try{
           annos=Integer.parseInt(experiencia);
       }catch(NumberFormatException e){
           annos = 0;
       }
       Persona persona = new Persona(0,nombres,apellidos,fecha,annos);
       try{
           ObjectMapper objectMapper = new ObjectMapper();
           String jsonString = objectMapper.writeValueAsString(persona);
           Message message = productorEJB.getSession().createTextMessage(jsonString);
           message.setStringProperty("TipoMensaje","Persona");
           productorEJB.enviarMensaje(message);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error al enviar los datos de la persona",
                   "Error",JOptionPane.ERROR_MESSAGE);
//           logger.error("Error al enviar los datos de la persona");
            return;
       }
       JOptionPane.showMessageDialog(null, "Se ha enviado los datos de la persona exitosamente",
               "Informacion",JOptionPane.INFORMATION_MESSAGE);       
              
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PersonasForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tExperiencia;
    private javax.swing.JTextField tFechaNac;
    private javax.swing.JTextField tNombres;
    // End of variables declaration//GEN-END:variables
}
